name: CI

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  DB_DATABASE: my_garage
  DB_USER: buggxs
  DB_PASSWORD: Hiwiegehts9
  JAVA_VERSION: 1.16

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Maven Clean Package and run tests
        run: |
          chmod +x mvnw && ./mvnw --no-transfer-progress clean package -P prod